### ISSUE TITLE
undefined method `parent_class' for #<RuboCop::AST::SendNode> on rspec tests

### ISSUE THREAD

**Issue by grepsedawk** [yarmiganosca/active_record_callbacks_cop#1]
When running this against many rspec tests, this fails with an error similar to:
undefined method `parent_class' for #<RuboCop::AST::SendNode:0x000055b791f213b0>

Example Code: [active_record_callbacks_cop-bug-report.zip](https://github.com/yarmiganosca/active_record_callbacks_cop/files/3399110/active_record_callbacks_cop-bug-report.zip)

**Comment by yarmiganosca** [comment]
Fixed in https://github.com/yarmiganosca/active_record_callbacks_cop/commit/b198b214f26839cde7ce6873162cb72c3a8381ed.
Fix released in gem version v0.1.1
